---

- name: Host | check ip is in hostfile
  ansible.builtin.shell: >
    set -o pipefail &&
    cat /etc/hosts | egrep -c '{{ ip.replace('\.', '\\.') }}'
  register: hosts_ip_entry_exists
  ignore_errors: true
  failed_when: false
  changed_when: false

- name: Host | check ip and hostname is in hostfile
  ansible.builtin.shell: >
    set -o pipefail &&
    cat /etc/hosts | egrep -c '{{ ip.replace('\.', '\\.') }}.*{{ hostname.replace('\.', '\\.') }}'
  register: hosts_entry_exists
  ignore_errors: true
  failed_when: false
  changed_when: false

- name: "Host | add host {{ hostname }} in hosts file if ip {{ ip }} entry does not exists"
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: '^{{ ip }}(.*)$'
    backrefs: yes
    line: '{{ ip }} {{ hostname }}\1'
    owner: root
    group: root
    mode: '0644'
  become: true
  changed_when: false
  # IPV6 have tendency to add some new entries every time
  when:
    - hosts_ip_entry_exists.rc == 0
    - hosts_ip_entry_exists.stdout != 0
    - hosts_entry_exists.rc == 1 or hosts_entry_exists.stdout == 0

- name: "Host | add host {{ hostname }} in hosts file if ip_entry {{ ip }} does not exist"
  ansible.builtin.lineinfile:
    path: /etc/hosts
    insertbefore: BOF
    line: '{{ ip }} {{ hostname }}'
    owner: root
    group: root
    mode: '0644'
  become: true
  changed_when: false
  # IPV6 have tendency to add some new entries every time
  when: >
    (hosts_ip_entry_exists is failed or
    hosts_ip_entry_exists.rc == 1 or
    hosts_ip_entry_exists.stdout == 0) and
    (hosts_entry_exists.rc == 1 or
    hosts_entry_exists.stdout == 0) and
    (ansible_facts['virtualization_type'] is not defined or ansible_facts['virtualization_type'] not in ['container'])
