---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
    requirements-file: requirements-collections.yml
driver:
  name: vagrant
  provider:
    name: virtualbox
platforms:
  - name: dns.osgiliath.test
    box: ${TESTBOX:-generic/fedora39}
    provider_options:
      cpus: 2
      memory: 4096
provisioner:
  name: ansible
  env:
    ANSIBLE_COLLECTIONS_PATH: "${MOLECULE_PROJECT_DIRECTORY}/../community-collections:${HOME}/.ansible/collections:/usr/share/ansible/collections"
  options:
    vvv: True
  config_options:
    defaults:
      remote_tmp: /tmp
verifier:
  name: testinfra
  env:
    PYTHONWARNINGS: "ignore:.*U.*mode is deprecated:DeprecationWarning"
  options:
    v: 1
scenario:
  name: default
