---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
    requirements-file: requirements-collections.yml
driver:
  name: vagrant
  provider:
    name: libvirt
platforms:
  - name: dns.osgiliath.test
    box: ${TESTBOX:-fedora/39-cloud-base}
    provider_options:
      driver: "kvm"
      cpus: 2
      memory: 2048
provisioner:
  name: ansible
  env:
    ANSIBLE_COLLECTIONS_PATH: "${MOLECULE_PROJECT_DIRECTORY}/../community-collections:${HOME}/.ansible/collections:/usr/share/ansible/collections"
  options:
    vvv: True
  config_options:
    defaults:
      remote_tmp: /tmp
      forks: 20
    ssh_connection:
      pipelining: true
      ssh_args: -o ControlMaster=auto -o ControlPersist=600s
verifier:
  name: testinfra
  env:
    PYTHONWARNINGS: "ignore:.*U.*mode is deprecated:DeprecationWarning"
  options:
    v: 1
scenario:
  name: kvm
